#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

# Create a sample index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx to redirect /redirect_me to another URL
sudo tee /etc/nginx/sites-available/default <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.techhub.com;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOL

sudo service nginx restart
