#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

# Create a sample index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Add the redirection rule to the Nginx configuration
sudo sed -i '/server_name _;/a \ \trewrite ^/redirect_me https://www.techhub.com permanent;' /etc/nginx/sites-enabled/default

sudo service nginx restart
