#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo tee /etc/nginx/sites-available/default <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.techhub.com;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOL
sudo service nginx restart
