#!/usr/bin/env bash
# same as task 0 but -f added to ln to forcefully remove the file if it exists
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-enabled/default
service nginx stop
rm /var/www/html/index.html
