#!/usr/bin/env bash
# display "Best School" 10 times using while but at the 9th iteration display Best school and then Hi on a new line
i=0
while [ $i -lt 10 ]; do
    if [ $i -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
