#!/usr/bin/env bash
# use while loop to dsiplay 1 to 10, at 4th display "bad luck", at 8th display "good luck", at 10th display "Best School"
i=1
while [ $i -le 10 ]; do
    if [ $i -eq 4 ]; then
        echo "bad luck"
    elif [ $i -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done