#!/usr/bin/env bash
# use while loop for 1 to 20, at 4th display 4 then "bad luck from china"
# at 9th display 9 then "bad luck from japan"
# at 17 display 17 then "bad luck from italy"
i=1
while [ $i -le 20  ]; do
	case $i in
        4)
            echo "$i"
            echo "bad luck from China"
            ;;
        9)
            echo "$i"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$i"
            echo "bad luck from Italy"
            ;;
        *)
            echo $i
            ;;
    esac
    ((i++))
done
