#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
hours=0
minutes=1
while [ $hours -le 12 ]; do
    echo "Hours: $hours"
    if [ $minutes -le 59 ]; then
        echo $minutes
    fi
    ((hours++))
done