#!/usr/bin/env bash
# Displays conten of pwd in a list format
for file in *; do
    if [ ! -f "$file" ] || [[ "$file" == .* ]]; then
        continue
    fi
    name=$(echo "$file" | cut -d'-' -f2-)
    echo "$name"
done