#!/usr/bin/env bash
# backup host files
cp /etc/hosts ~/etc/hosts.bak
# create new host files
cp /etc/hosts ~/hosts.new
# sed ... ~/hosts.new
echo 127.0.0.2 localhost >> ~/hosts.new
echo 8.8.8.8 facebook.com >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
